var DRAW_INTERVAL_MS = 1000 / 60;
var CANVAS_WIDTH = 700;
var CANVAS_HEIGHT = 540;

var KEY_UP = 87;
var KEY_RIGHT = 68;
var KEY_DOWN = 83;
var KEY_LEFT = 65;

var SPEED_MOVE = 2.5;
var WALL_SPEED_MOVE = 1;
var FRICTION = 0.1;

var WALL_INTERVAL = 200;
var COIN_INTERVAL = 50;

var SHOOTS_PLAYER_SPEED = 5;

var score = 0;
